#!/bin/sh

TMP=/tmp/sc.png

scrot -s "$TMP"
which optipng >/dev/null && optipng "$TMP"

# echo "<img src='data:image/png;base64,"$(base64 -w0 "$TMP")"' />" | \
#  	xclip -selection clipboard -t text/html

xclip -selection clipboard -t image/png <"$TMP"

rm -f "$TMP"
